version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ifindy
    image: ifindy
    ports:
      - '3000:3000'
    networks:
      - 'app-network'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mysql://root:admin@db:3306/metafy
    
  db:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - 'app-network'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: metafy
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin

volumes:
  mysql-data:
    
networks:
  app-network:
