version: '3.7'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: fiap
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin

volumes:
  mysql-data:
